//! Snapshot hyperlink entry encoding.
//!
//! Each entry contains a URI and either an implicit numeric ID or an explicit
//! byte-string ID. Implicit IDs are generated by the terminal when the source
//! hyperlink has no explicit ID. A record can use these entries to build a
//! hyperlink table and assign indexes according to that record's format.
//! Indexing and ordering are properties of the containing record rather than
//! this codec.
//!
//! IDs and URIs are arbitrary byte strings. Their lengths are retained on the
//! wire; they are not NUL-terminated and need not contain UTF-8.
//!
//! All integers are unsigned and little-endian.
//!
//! ## Implicit ID
//!
//! | Offset | Size      | Field              |
//! | -----: | --------: | :----------------- |
//! |      0 |         1 | Kind, `1`          |
//! |      1 |         4 | Implicit ID (`u32`) |
//! |      5 |         4 | URI length (`u32`) |
//! |      9 | `uri_len` | URI bytes          |
//!
//! ## Explicit ID
//!
//! | Offset       | Size      | Field                      |
//! | -----------: | --------: | :------------------------- |
//! |            0 |         1 | Kind, `2`                  |
//! |            1 |         4 | Explicit ID length (`u32`) |
//! |            5 |  `id_len` | Explicit ID bytes          |
//! | `5 + id_len` |         4 | URI length (`u32`)         |
//! | `9 + id_len` | `uri_len` | URI bytes                  |
//!
//! Both variants have nine bytes of fixed overhead. The remaining bytes are
//! the URI plus the explicit ID, when present.
//!
//! Decoding never allocates. The caller provides storage for the explicit ID
//! and URI bytes, and the returned hyperlink borrows slices of that storage.

const std = @import("std");
const io = @import("io.zig");
const terminal_hyperlink = @import("../hyperlink.zig");

const Kind = enum(u8) {
    implicit = 1,
    explicit = 2,
};

/// Errors possible while determining encoded string lengths.
pub const StringBytesError = error{
    /// A string cannot fit its `u32` length or local size arithmetic overflowed.
    StringTooLong,
};

/// Errors possible while encoding one hyperlink entry.
pub const EncodeError = std.Io.Writer.Error || StringBytesError;

/// Errors possible while decoding one hyperlink entry.
pub const DecodeError = std.Io.Reader.Error || error{
    /// The hyperlink kind is not defined by snapshot version 0.
    InvalidKind,

    /// Caller-provided string storage cannot hold the decoded entry.
    BufferTooSmall,
};

/// One decoded hyperlink and the number of caller-owned string bytes it uses.
pub const Decoded = struct {
    value: terminal_hyperlink.Hyperlink,
    string_bytes: usize,
};

/// Return the raw explicit-ID and URI bytes encoded by `value`.
///
/// Length prefixes and the numeric implicit ID are not included.
pub fn stringBytes(
    value: terminal_hyperlink.Hyperlink,
) StringBytesError!usize {
    _ = std.math.cast(u32, value.uri.len) orelse {
        return error.StringTooLong;
    };
    var result = value.uri.len;

    switch (value.id) {
        .implicit => {},
        .explicit => |id| {
            _ = std.math.cast(u32, id.len) orelse {
                return error.StringTooLong;
            };
            result = std.math.add(usize, result, id.len) catch {
                return error.StringTooLong;
            };
        },
    }

    return result;
}

/// Return the complete encoded length of one hyperlink entry.
pub fn encodedLen(
    value: terminal_hyperlink.Hyperlink,
) StringBytesError!usize {
    const string_bytes = try stringBytes(value);
    return std.math.add(usize, 9, string_bytes) catch {
        return error.StringTooLong;
    };
}

/// Encode one hyperlink entry.
pub fn encode(
    value: terminal_hyperlink.Hyperlink,
    writer: *std.Io.Writer,
) EncodeError!void {
    // Validate every length before writing any part of the entry.
    _ = try stringBytes(value);

    switch (value.id) {
        .implicit => |id| {
            try writer.writeByte(@intFromEnum(Kind.implicit));
            try io.writeInt(writer, u32, id);
            try io.writeInt(writer, u32, @intCast(value.uri.len));
            try writer.writeAll(value.uri);
        },
        .explicit => |id| {
            try writer.writeByte(@intFromEnum(Kind.explicit));
            try io.writeInt(writer, u32, @intCast(id.len));
            try writer.writeAll(id);
            try io.writeInt(writer, u32, @intCast(value.uri.len));
            try writer.writeAll(value.uri);
        },
    }
}

/// Decode one hyperlink entry into caller-owned string storage.
///
/// The returned hyperlink remains valid only as long as `strings` remains
/// valid and unmodified. `string_bytes` identifies the prefix of `strings`
/// used by this entry.
pub fn decode(
    reader: *std.Io.Reader,
    strings: []u8,
) DecodeError!Decoded {
    const kind_raw = try reader.takeByte();
    const kind = std.enums.fromInt(Kind, kind_raw) orelse {
        return error.InvalidKind;
    };

    return switch (kind) {
        .implicit => decodeImplicit(reader, strings),
        .explicit => decodeExplicit(reader, strings),
    };
}

fn decodeImplicit(
    reader: *std.Io.Reader,
    strings: []u8,
) DecodeError!Decoded {
    const id = try io.readInt(reader, u32);
    const uri_len: usize = @intCast(try io.readInt(reader, u32));
    if (uri_len > strings.len) return error.BufferTooSmall;

    const uri = strings[0..uri_len];
    try reader.readSliceAll(uri);
    return .{
        .value = .{
            .id = .{ .implicit = id },
            .uri = uri,
        },
        .string_bytes = uri.len,
    };
}

fn decodeExplicit(
    reader: *std.Io.Reader,
    strings: []u8,
) DecodeError!Decoded {
    const id_len: usize = @intCast(try io.readInt(reader, u32));
    if (id_len > strings.len) return error.BufferTooSmall;

    const id = strings[0..id_len];
    try reader.readSliceAll(id);

    const uri_len: usize = @intCast(try io.readInt(reader, u32));
    const remaining = strings[id.len..];
    if (uri_len > remaining.len) return error.BufferTooSmall;

    const uri = remaining[0..uri_len];
    try reader.readSliceAll(uri);
    return .{
        .value = .{
            .id = .{ .explicit = id },
            .uri = uri,
        },
        .string_bytes = id.len + uri.len,
    };
}

test "golden implicit encoding" {
    const value: terminal_hyperlink.Hyperlink = .{
        .id = .{ .implicit = 0x01020304 },
        .uri = "uri",
    };

    var buf: [encodedLen(value) catch unreachable]u8 = undefined;
    var writer: std.Io.Writer = .fixed(&buf);
    try encode(value, &writer);

    try std.testing.expectEqualStrings(
        "\x01\x04\x03\x02\x01\x03\x00\x00\x00uri",
        writer.buffered(),
    );
    try std.testing.expectEqual(@as(usize, 3), try stringBytes(value));
}

test "golden explicit encoding" {
    const value: terminal_hyperlink.Hyperlink = .{
        .id = .{ .explicit = "id" },
        .uri = "uri",
    };

    var buf: [encodedLen(value) catch unreachable]u8 = undefined;
    var writer: std.Io.Writer = .fixed(&buf);
    try encode(value, &writer);

    try std.testing.expectEqualStrings(
        "\x02\x02\x00\x00\x00id\x03\x00\x00\x00uri",
        writer.buffered(),
    );
    try std.testing.expectEqual(@as(usize, 5), try stringBytes(value));
}

test "empty strings round trip" {
    const values = .{
        terminal_hyperlink.Hyperlink{
            .id = .{ .implicit = 0 },
            .uri = "",
        },
        terminal_hyperlink.Hyperlink{
            .id = .{ .explicit = "" },
            .uri = "",
        },
    };

    inline for (values) |value| {
        var encoded: [9]u8 = undefined;
        var writer: std.Io.Writer = .fixed(&encoded);
        try encode(value, &writer);

        var reader: std.Io.Reader = .fixed(writer.buffered());
        var strings: [0]u8 = .{};
        const decoded = try decode(&reader, &strings);
        try std.testing.expectEqual(@as(usize, 0), decoded.string_bytes);
        try std.testing.expectEqualStrings("", decoded.value.uri);
        switch (value.id) {
            .implicit => |id| try std.testing.expectEqual(
                id,
                decoded.value.id.implicit,
            ),
            .explicit => |id| try std.testing.expectEqualStrings(
                id,
                decoded.value.id.explicit,
            ),
        }
    }
}

test "decode with a one-byte reader buffer" {
    const fixture =
        "\x01\x04\x03\x02\x01\x03\x00\x00\x00uri" ++
        "\x02\x02\x00\x00\x00id\x03\x00\x00\x00uri";
    var source: std.Io.Reader = .fixed(fixture);
    var read_buf: [1]u8 = undefined;
    var limited = source.limited(.unlimited, &read_buf);

    var implicit_strings: [3]u8 = undefined;
    const implicit = try decode(&limited.interface, &implicit_strings);
    try std.testing.expectEqual(@as(usize, 3), implicit.string_bytes);
    try std.testing.expectEqualStrings("uri", implicit.value.uri);
    try std.testing.expectEqual(
        @as(u32, 0x01020304),
        implicit.value.id.implicit,
    );

    var explicit_strings: [5]u8 = undefined;
    const explicit = try decode(&limited.interface, &explicit_strings);
    try std.testing.expectEqual(@as(usize, 5), explicit.string_bytes);
    try std.testing.expectEqualStrings("id", explicit.value.id.explicit);
    try std.testing.expectEqualStrings("uri", explicit.value.uri);
}

test "reject invalid kinds" {
    inline for (.{ 0, 3, std.math.maxInt(u8) }) |kind| {
        var fixture: [1]u8 = .{kind};
        var reader: std.Io.Reader = .fixed(&fixture);
        var strings: [0]u8 = .{};
        try std.testing.expectError(
            error.InvalidKind,
            decode(&reader, &strings),
        );
    }
}

test "reject insufficient string storage" {
    {
        var reader: std.Io.Reader = .fixed(
            "\x01\x04\x03\x02\x01\x03\x00\x00\x00uri",
        );
        var strings: [2]u8 = undefined;
        try std.testing.expectError(
            error.BufferTooSmall,
            decode(&reader, &strings),
        );
    }

    {
        var reader: std.Io.Reader = .fixed(
            "\x02\x03\x00\x00\x00id!\x03\x00\x00\x00uri",
        );
        var strings: [2]u8 = undefined;
        try std.testing.expectError(
            error.BufferTooSmall,
            decode(&reader, &strings),
        );
    }

    {
        var reader: std.Io.Reader = .fixed(
            "\x02\x02\x00\x00\x00id\x03\x00\x00\x00uri",
        );
        var strings: [4]u8 = undefined;
        try std.testing.expectError(
            error.BufferTooSmall,
            decode(&reader, &strings),
        );
    }
}

test "reject every truncation" {
    const fixtures = .{
        "\x01\x04\x03\x02\x01\x03\x00\x00\x00uri",
        "\x02\x02\x00\x00\x00id\x03\x00\x00\x00uri",
    };

    inline for (fixtures) |fixture| {
        for (0..fixture.len) |fixture_len| {
            var reader: std.Io.Reader = .fixed(fixture[0..fixture_len]);
            var strings: [5]u8 = undefined;
            try std.testing.expectError(
                error.EndOfStream,
                decode(&reader, &strings),
            );
        }
    }
}
